= Red Hat Developer Hub Administration
:navtitle: Home

== Introduction

Welcome to this quick course on the _Red Hat Developer Hub Administration_.
This course is the `second` in a series of `three` courses about Red Hat Developer Hub:

1. https://redhatquickcourses.github.io/devhub-intro[Introduction to Red Hat Developer Hub^]
2. Red Hat Developer Hub Administration  (_This course_)
3. https://redhatquickcourses.github.io/devhub-build[Building Developer Portals with Red Hat Developer Hub^]

This course covers the install, updates and uninstall process for Red Hat Developer Hub (RHDH). You also learn about the basics of configuration in RHDH, and how to configure authentication using GitHub along with configuring authorization policies using Role Based Access Control (RBAC).

NOTE: The hands-on labs for this course have been tested on *RHDH 1.4*. The labs should mostly work in minor update releases of RHDH. If you encounter any issues, please open a GitHub issue in the course repository.

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Ravi Srinivasan
* Jason Froehlich
* Hans-Peter Grahsl
* Rafael Soares
* Tyrell Reddy and the entire Demo Platform (RHDP) Team
* Rigin Oommen

== Classroom Environment

=== For Red Hat Associates

Red Hat associates and others who have access to the Red Hat Demo Platform (RHDP) should use the https://demo.redhat.com/catalog?search=single&item=babylon-catalog-prod%2Fopenshift-cnv.ocpmulti-single-node-cnv.prod[OpenShift Single Node Cluster^] catalog item.

This classroom does *NOT* have RHDH pre-installed. You install and configure a basic RHDH instance, and then continue using this instance with other courses in the learning path.

Log in to RHDP and click `Order` to request a new SNO cluster. In the order page for the catalog item, do the following:

* *Activity*: Select `Practice/Enablement`
* *Purpose*: Select `Learning about the Product`
* *Salesforce ID*: If you have an opportunity ID, enter it into this field, otherwise leave this field blank
* *Features*: Select `true`
* *OpenShift node cores*: `16`
* *OpenShift node memory size*: `32GB`
* *OpenShift Version*: `4.15` or higher

Select the checkbox at the bottom of the page to confirm that lab costs will be charged to your cost center, and click `Order`.

The lab environment will take an hour to provision. You can check the status and details of the OpenShift cluster from the `Services` page of RHDP.

=== For Red Hat Partners

Red Hat partners and others who do not have access to RHDP, should provision their own Red Hat OpenShift 4.15 cluster using the Red Hat Hybrid Cloud Console at https://console.redhat.com/openshift/overview. Ensure that you provision an OpenShift 4.15 cluster with at least 8 vCPUs and 32GB of RAM.

NOTE: You can also install RHDH and run the hands-on labs using OpenShift Local, provided you allocate a minimum of 8 vCPUs and 24GB+ RAM. Go to https://developers.redhat.com/products/openshift-local/overview and click on `Install OpenShift on your laptop`.

== Prerequisites

* Basic knowledge of OpenShift (or Kubernetes) administration
* Knowledge of building Docker or Podman containers.
* Deploying container images on OpenShift or Kubernetes
* OpenShift or Kubernetes User and Role administration

== Objectives

The overall objectives of this course include:

* Install, Upgrade and Uninstall Red Hat Developer Hub on OpenShift
* Perform basic configuration of RHDH
* Configure single sign-on and user authentication for Red Hat Developer Hub using GitHub
* Configure authorization policies using Role Based Access Control (RBAC)
