# Configuring Authentication using GitHub
:navtitle: GitHub Authentication

The authentication system in RHDH is handled by *Authentication Providers*. RHDH uses the providers to access identity and user information, which can be used to delegate access rights to various plugins and services in RHDH. You can configure RHDH to have multiple authentication providers, with only *ONE* provider being actively used at any given time for logging in users.

RHDH supports many common authentication providers by default like GitHub, GitLab, Auth0, Okta, Keycloak, and more. Consult the references section for the full list.

NOTE: Authentication providers are responsible *only* for authenticating the *identity* of the user, and passing on this information to RHDH. Authorization, that is, *what* actions an authenticated identity can perform in RHDH are handled by a different component of RHDH called *Role Based Access Control (RBAC)* using *Permissions Policies*. RBAC is covered in a separate section of this course.

Consider the scenario where your organization's developers use GitHub to manage source code. You would ideally like developers to use their GitHub credentials to log in to RHDH, and also import team and user information from GitHub. Very often, developers are added to a GitHub `Organization` to manage groups of developers. The following exercise configures RHDH to use GitHub for authentication, and imports the GitHub organization member and team details into the RHDH database.

## Lab: Configuring Authentication using GitHub

### Pre-requisites

* A GitHub account
* Administrator rights to a GitHub Organization (Create a new Github Org if it does not exist)
* OpenShift cluster administrator access
* Ability to create `GitHub Apps` on GitHub

Configuring GitHub for RHDH authentication involves two major steps:

* Create a new GitHub App for your GitHub organization
* Edit the `app-config-rhdh` ConfigMap and configure RHDH to use the GitHub App for authentication. To prevent storing credentials in plain text in the ConfigMap, you will embed the credentials for GitHub in a secret, and then refer the secret in the `app-config-rhdh` ConfigMap.

### Create a new GitHub App

. Navigate to https://github.com/organizations/<YOUR_ORGANIZATION>/settings/apps, and then click `New GitHub App`.
. In the `Register new GitHub App` page, fill out the following details:

* `GitHub App name`: *rhdh-app-<your_RHDP_GUID>*
* `Homepage URL`: *https://rhdh-developer-hub-devhub.apps.cluster-<GUID>.dynamic.redhatworkshops.io* (Your RHDH Route URL)
* `Callback URL`: *https://rhdh-developer-hub-devhub.apps.cluster-<GUID>.dynamic.redhatworkshops.io/api/auth/github/handler/frame*
* `Webhook URL`: *https://rhdh-developer-hub-devhub.apps.cluster-<GUID>.dynamic.redhatworkshops.io*
* `Webhook secret`: *5up3rS3cret* (Provide a strong secret)
* Under `Permissions`, expand `Repository Permissions` and ensure that you provide at least `Read-only` access to the GitHub features you would like to integrate from RHDH. At a minimum, toggle the following permissions:
** Administration
** Commit statuses
** Contents
** Dependabot
** Deployments
** Pull Requests
** Webhooks
* Toggle other permissions as per your needs.
* Under `Organization permissions`, ensure that you toggle `Read-only` permissions for `Members` so that RHDH can import team and user information from GitHub.
* Select `Only on this account` for the `Where can this GitHub App be installed?` option.
. Verify your form entries, and when you are satisfied click `Create GitHub App`.
. You will be shown your `App ID` and a client ID. Make note of these values for the next step.
. Click `Generate a new client secret`. Copy the generated secret for the next steps.
. Scroll down to the `Private Keys` section and click `Generate a private key`. Copy the generated private key certificate (it is in PEM format) to a safe location.
. In the left sidebar menu of the generated app, select `Install App`, and then click `Install`.
. Select `All Repositories` for `Repository access` and then click `Install`.

### Create a Secret to Store GitHub App Credentials

Rather than store the GitHub App credentials in plain text directly in the `app-config-rhdh` ConfigMap, you will create a secret to store the credentials. You will then refer to the credentials as environment variables in the ConfigMap.

. Create a file named `env.sh` with the following environment variables and replace the values with the GitHub App details you created in the previous step.
+
[subs=+quotes]
----
export OPENSHIFT_CLUSTER_INFO=$(oc cluster-info | head -n 1 | sed 's/^.*https...api//' | sed 's/.6443.*$//')
export K8S_CLUSTER_API=$(oc cluster-info | head -n 1 |  sed 's/^.*https/https/')

export GITHUB_HOST_DOMAIN=github.com
export GITHUB_ORGANIZATION='Your Org Name'
export GITHUB_ORG_URL=https://$GITHUB_HOST_DOMAIN/$GITHUB_ORGANIZATION

export GITHUB_APP_ID='Your App ID'
export GITHUB_APP_CLIENT_ID='Your client ID'
export GITHUB_APP_CLIENT_SECRET='Your client secret'
export GITHUB_APP_PRIVATE_KEY_FILE="$(< rhdh-app-<guid>.2024-01-17.private-key.pem)"

export GITHUB_APP_WEBHOOK_URL='https://rhdh-developer-hub-devhub.apps.cluster-<guid>.dynamic.redhatworkshops.io'
export GITHUB_APP_WEBHOOK_SECRET='Your webhook secret'
----

. Log in to the OpenShift cluster as the `admin` user using the `oc` CLI.
. Switch to the `devhub` namespace where you installed RHDH.
. Source the `env.sh` file to export the environment variables:
+
[subs=+quotes]
----
$ source env.sh
----

. Create a secret named `rhdh-secrets` to store the credentials:
+
[subs=+quotes]
----
$ oc create secret generic rhdh-secrets -n devhub \
--from-literal=GITHUB_ORG_URL=$GITHUB_ORG_URL \
--from-literal=GITHUB_APP_ID=$GITHUB_APP_ID \
--from-literal=GITHUB_APP_CLIENT_ID=$GITHUB_APP_CLIENT_ID \
--from-literal=GITHUB_APP_CLIENT_SECRET=$GITHUB_APP_CLIENT_SECRET \
--from-literal=GITHUB_APP_PRIVATE_KEY_FILE=$GITHUB_APP_PRIVATE_KEY_FILE \
--from-literal=GITHUB_APP_WEBHOOK_URL=$GITHUB_APP_WEBHOOK_URL \
--from-literal=GITHUB_APP_WEBHOOK_SECRET=$GITHUB_APP_WEBHOOK_SECRET
----

### Configure RHDH for GitHub Authentication

. Log in to the OpenShift web console as the `admin` user and switch to the `Developer Perspective`.
. Click `ConfigMaps` and select the `app-config-rhdh`. Toggle the `YAML` tab to switch to YAML editing mode.
. Add the following YAML configuration at the same indentation level as the `app` attribute. Note the reference to environment variables instead of hard code credentials:
+
[subs=+quotes]
----
...
data:
  app-config-rhdh.yaml: |
app:
  title: Red Hat Developer Hub
*integrations:
      github:
        - host: github.com
          apps:
            - appId: ${GITHUB_APP_ID}
              clientId: ${GITHUB_APP_CLIENT_ID}
              clientSecret: ${GITHUB_APP_CLIENT_SECRET}
              webhookUrl: ${GITHUB_APP_WEBHOOK_URL}
              webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
              privateKey: |
                ${GITHUB_APP_PRIVATE_KEY_FILE}
    auth:
      environment: development
      providers:
        github:
          development:
            clientId: ${GITHUB_APP_CLIENT_ID}
            clientSecret: ${GITHUB_APP_CLIENT_SECRET}
    enabled:
      github: true
      githubOrg: true*
----

### Configure RHDH to Import Users and Groups in a GitHub Organization

. To enable GitHub Organization member discovery, add the following YAML configuration at the same indentation level as the `enabled` attribute:
+
[subs=+quotes]
----
    enabled:
      github: true
      githubOrg: true
    *catalog:
      providers:
        githubOrg:
          default:
            id: development
            orgUrl: ${GITHUB_ORG_URL}*
----

. Click `Save`.

### Upgrade RHDH Helm Chart

The final step is to inject the secret you created with the GitHub App credentials into the RHDH container. You do this by editing the helm chart configuration and refer to the `rhdh-secrets`. You will also enable the `GitHub Organization discovery` dynamic plugin.

. Edit the `rhdh` helm chart, toggle `Form view`, and expand `Root Schema > global > Dynamic plugins configuration > List of dynamic plugins that should be installed in the backstage application`. Add the value `./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-github-org-dynamic` to the `Package specification...` field. This value enables the dynamic plugin for GitHub Organization discovery.

. Next, expand `Root Schema > Backstage chart schema > Backstage parameters > Backstage container environment variables from existing Secrets` and add `rhdh-secrets` to refer to the secret you created earlier.

. Click `Upgrade`.

. Wait for a few minutes while the helm chart is upgraded, and the RHDH pod is re-created with the new configuration.

### Verify User Sign In

. If you are signed in as a `Guest` RHDH user, then sign out by selecting the `Sign Out` (expand the `...` next to the Profile card) in the `Settings > Profile` page.
. Sign in using `GitHub` sign-in method in the RHDH home page
. You will be re-directed to a GitHub prompt asking you to sign in using your GitHub credentials.
. After you are signed in, navigate to the `Settings` page. Notice that GitHub has authenticated the user and provided identity information to RHDH.
. Click on the logged in `User Entity` in the `Settings` page to view the detail imported from GitHub.
. Click on the RHDH `Catalog` in the sidebar. Select the `Kind` drop-down, and note that two new entities called `User` and `Group` are now visible.
. Select `Group` in the `Kind` drop-down to view the teams (mapped into RHDH Groups) imported from the GitHub organization.
. Select `User` in the `Kind` drop-down to view the users imported from the GitHub organization.

NOTE: There is a known issue in the RHDH 1.0 version, where it may take more than 30 minutes for the GitHub Organization member discovery plugin to fetch data from GitHub. The schedule is unfortunately fixed and hard-coded in the plugin. This issue will be fixed in a future dot release of the product.

## References

* https://backstage.io/docs/auth[Authentication providers in Backstage^]
* https://backstage.io/docs/overview/threat-model#integrator-responsibilities[Backstage Security Threat Model^]
* https://access.redhat.com/documentation/en-us/red_hat_developer_hub/1.0/html-single/getting_started_with_red_hat_developer_hub/index#setting-github-integration-and-authentication[Set up GitHub Authentication^]
* https://backstage.io/docs/integrations/github/github-apps#app-permissions[Required GitHub App Permissions^]